version: '3'
services:
  ghp:
    image: jekyll/jekyll
    volumes:
    - .:/app
    - /usr/local/bundle
    working_dir: /app
    ports:
    - 4000:4000
    command:
      - /bin/sh
      - -c
      - |
        jekyll serve
